name: Convertir Word a PDF

on:
  push:

jobs:
  convertir:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Mostrar archivos existentes
        run: |
          echo "Contenido del repositorio:"
          ls -la

      - name: Convertir DOCX a PDF
        run: |
          mkdir salida
          libreoffice --headless --convert-to pdf probando.docx --outdir salida

      - name: Verificar PDF generado
        run: |
          echo "Archivos generados:"
          ls -la salida

      - name: Guardar PDF como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Generado
          path: salida/documento.pdf
