name: CI/CD de documentos

on:
  push:
    paths:
      - '**.docx'

jobs:
  ci_convertir:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar LibreOffice
        run: sudo apt-get update && sudo apt-get install -y libreoffice

      - name: Convertir Word a PDF
        run: libreoffice --headless --convert-to pdf *.docx --outdir pdfs

  cd_publicar:
    runs-on: ubuntu-latest
    needs: ci_convertir
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Subir PDFs convertidos
        uses: actions/upload-artifact@v4
        with:
          name: documentos-pdf
          path: pdfs/*.pdf
