name: Saludo automático
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Crear página HTML
        run: |
          echo "<html><body><h1>Hola alumnos 👩‍🏫</h1>" > index.html
          echo "<p>Este mensaje se desplegó automáticamente con CD.</p>" >> index.html
          echo "<p>Hora Argentina: $(TZ=America/Argentina/Buenos_Aires date)</p>" >> index.html
          echo "</body></html>" >> index.html

      - name: Deploy en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
